--Data cleaning

let
    Source = Excel.Workbook(File.Contents("C:\Users\oryim\Downloads\Power BI - Final Project.xlsx"), null, true),
    #"Data Professional Survey_Sheet" = Source{[Item="Data Professional Survey",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Data Professional Survey_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Unique ID", type text}, {"Email", type text}, {"Date Taken (America/New_York)", type date}, {"Time Taken (America/New_York)", type time}, {"Browser", type text}, {"OS", type text}, {"City", type text}, {"Country", type text}, {"Referrer", type text}, {"Time Spent", type time}, {"Q1 - Which Title Best Fits your Current Role?", type text}, {"Q2 - Did you switch careers into Data?", type text}, {"Q3 - Current Yearly Salary (in USD)", type text}, {"Q4 - What Industry do you work in?", type text}, {"Q5 - Favorite Programming Language", type text}, {"Q6 - How Happy are you in your Current Position with the following? (Salary)", Int64.Type}, {"Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)", Int64.Type}, {"Q6 - How Happy are you in your Current Position with the following? (Coworkers)", Int64.Type}, {"Q6 - How Happy are you in your Current Position with the following? (Management)", Int64.Type}, {"Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)", Int64.Type}, {"Q6 - How Happy are you in your Current Position with the following? (Learning New Things)", Int64.Type}, {"Q7 - How difficult was it for you to break into Data?", type text}, {"Q8 - If you were to look for a new job today, what would be the most important thing to you?", type text}, {"Q9 - Male/Female?", type text}, {"Q10 - Current Age", Int64.Type}, {"Q11 - Which Country do you live in?", type text}, {"Q12 - Highest Level of Education", type text}, {"Q13 - Ethnicity", type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Browser", "OS", "City", "Country", "Referrer"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns", each true),
    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows1",{"Email"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Columns1", "Q3 - Current Yearly Salary (in USD)", "Q3 - Current Yearly Salary (in USD) - Copy"),
    #"Split Column by Character Transition" = Table.SplitColumn(#"Duplicated Column", "Q3 - Current Yearly Salary (in USD) - Copy", Splitter.SplitTextByCharacterTransition({"0".."9"}, (c) => not List.Contains({"0".."9"}, c)), {"Q3 - Current Yearly Salary (in USD) - Copy.1", "Q3 - Current Yearly Salary (in USD) - Copy.2", "Q3 - Current Yearly Salary (in USD) - Copy.3"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Split Column by Character Transition",{"Q3 - Current Yearly Salary (in USD) - Copy.3"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns2","k","",Replacer.ReplaceText,{"Q3 - Current Yearly Salary (in USD) - Copy.2"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","-","",Replacer.ReplaceText,{"Q3 - Current Yearly Salary (in USD) - Copy.2"}),
    #"Filtered Rows2" = Table.SelectRows(#"Replaced Value1", each true),
    #"Replaced Value2" = Table.ReplaceValue(#"Filtered Rows2","+","225",Replacer.ReplaceText,{"Q3 - Current Yearly Salary (in USD) - Copy.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value2",{{"Q3 - Current Yearly Salary (in USD) - Copy.2", Int64.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Average Income", each ([#"Q3 - Current Yearly Salary (in USD) - Copy.1"]) + ([#"Q3 - Current Yearly Salary (in USD) - Copy.2"])/2),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Q3 - Current Yearly Salary (in USD) - Copy.1", Int64.Type}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Changed Type2",{"Average Income"}),
    #"Added Custom1" = Table.AddColumn(#"Removed Columns3", "Average Income", each ([#"Q3 - Current Yearly Salary (in USD) - Copy.1"]) + ([#"Q3 - Current Yearly Salary (in USD) - Copy.2"])/2),
    #"Rounded Up" = Table.TransformColumns(#"Added Custom1",{{"Average Income", Number.RoundUp, Int64.Type}}),
    #"Removed Columns4" = Table.RemoveColumns(#"Rounded Up",{"Q3 - Current Yearly Salary (in USD) - Copy.2", "Q3 - Current Yearly Salary (in USD) - Copy.1"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns4",{"Unique ID", "Date Taken (America/New_York)", "Time Taken (America/New_York)", "Time Spent", "Q1 - Which Title Best Fits your Current Role?", "Q2 - Did you switch careers into Data?", "Q3 - Current Yearly Salary (in USD)", "Average Income", "Q4 - What Industry do you work in?", "Q5 - Favorite Programming Language", "Q6 - How Happy are you in your Current Position with the following? (Salary)", "Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)", "Q6 - How Happy are you in your Current Position with the following? (Coworkers)", "Q6 - How Happy are you in your Current Position with the following? (Management)", "Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)", "Q6 - How Happy are you in your Current Position with the following? (Learning New Things)", "Q7 - How difficult was it for you to break into Data?", "Q8 - If you were to look for a new job today, what would be the most important thing to you?", "Q9 - Male/Female?", "Q10 - Current Age", "Q11 - Which Country do you live in?", "Q12 - Highest Level of Education", "Q13 - Ethnicity"}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Reordered Columns", "Q11 - Which Country do you live in?", "Q11 - Which Country do you live in? - Copy"),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Column1", "Q11 - Which Country do you live in? - Copy", Splitter.SplitTextByEachDelimiter({":"}, QuoteStyle.None, false), {"Q11 - Which Country do you live in? - Copy.1", "Q11 - Which Country do you live in? - Copy.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Q11 - Which Country do you live in? - Copy.1", type text}, {"Q11 - Which Country do you live in? - Copy.2", type text}}),
    #"Filtered Rows3" = Table.SelectRows(#"Changed Type3", each true),
    #"Replaced Value3" = Table.ReplaceValue(#"Filtered Rows3",null,"",Replacer.ReplaceValue,{"Q11 - Which Country do you live in? - Copy.2"}),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Replaced Value3", "Q11 - Which Country do you live in? - Copy.1", "Q11 - Which Country do you live in? - Copy.1 - Copy"),
    #"Replaced Value4" = Table.ReplaceValue(#"Duplicated Column2","Other (Please Specify)","",Replacer.ReplaceText,{"Q11 - Which Country do you live in? - Copy.1 - Copy"}),
    #"Merged Columns" = Table.CombineColumns(#"Replaced Value4",{"Q11 - Which Country do you live in? - Copy.1 - Copy", "Q11 - Which Country do you live in? - Copy.2"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Country of Residence"),
    #"Filtered Rows4" = Table.SelectRows(#"Merged Columns", each true),
    #"Replaced Value5" = Table.ReplaceValue(#"Filtered Rows4","Other (Please Specify)","NA",Replacer.ReplaceText,{"Country of Residence"}),
    #"Filtered Rows5" = Table.SelectRows(#"Replaced Value5", each true),
    #"Replaced Value6" = Table.ReplaceValue(#"Filtered Rows5","","NA",Replacer.ReplaceValue,{"Country of Residence"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Replaced Value6",{"Q11 - Which Country do you live in? - Copy.1"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns5",{"Unique ID", "Date Taken (America/New_York)", "Time Taken (America/New_York)", "Time Spent", "Q1 - Which Title Best Fits your Current Role?", "Q2 - Did you switch careers into Data?", "Q3 - Current Yearly Salary (in USD)", "Average Income", "Q4 - What Industry do you work in?", "Q5 - Favorite Programming Language", "Q6 - How Happy are you in your Current Position with the following? (Salary)", "Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)", "Q6 - How Happy are you in your Current Position with the following? (Coworkers)", "Q6 - How Happy are you in your Current Position with the following? (Management)", "Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)", "Q6 - How Happy are you in your Current Position with the following? (Learning New Things)", "Q7 - How difficult was it for you to break into Data?", "Q8 - If you were to look for a new job today, what would be the most important thing to you?", "Q9 - Male/Female?", "Q10 - Current Age", "Country of Residence", "Q11 - Which Country do you live in?", "Q12 - Highest Level of Education", "Q13 - Ethnicity"}),
    #"Removed Columns6" = Table.RemoveColumns(#"Reordered Columns1",{"Q11 - Which Country do you live in?"}),
    #"Filtered Rows6" = Table.SelectRows(#"Removed Columns6", each true),
    #"Replaced Value7" = Table.ReplaceValue(#"Filtered Rows6","","N/A",Replacer.ReplaceValue,{"Q12 - Highest Level of Education"}),
    #"Filtered Rows7" = Table.SelectRows(#"Replaced Value7", each true),
    #"Replaced Value8" = Table.ReplaceValue(#"Filtered Rows7","NA","N/A",Replacer.ReplaceText,{"Country of Residence"}),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Replaced Value8", "Q4 - What Industry do you work in?", "Q4 - What Industry do you work in? - Copy"),
    #"Duplicated Column4" = Table.DuplicateColumn(#"Duplicated Column3", "Q4 - What Industry do you work in? - Copy", "Q4 - What Industry do you work in? - Copy - Copy"),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Duplicated Column4", "Q4 - What Industry do you work in? - Copy - Copy", Splitter.SplitTextByEachDelimiter({":"}, QuoteStyle.None, false), {"Q4 - What Industry do you work in? - Copy - Copy.1", "Q4 - What Industry do you work in? - Copy - Copy.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Q4 - What Industry do you work in? - Copy - Copy.1", type text}, {"Q4 - What Industry do you work in? - Copy - Copy.2", type text}}),
    #"Replaced Value9" = Table.ReplaceValue(#"Changed Type4",null,"",Replacer.ReplaceValue,{"Q4 - What Industry do you work in? - Copy - Copy.2"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","Other (Please Specify)","",Replacer.ReplaceText,{"Q4 - What Industry do you work in? - Copy - Copy.1"}),
    #"Merged Columns1" = Table.CombineColumns(#"Replaced Value10",{"Q4 - What Industry do you work in? - Copy - Copy.2", "Q4 - What Industry do you work in? - Copy - Copy.1"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Work Industry"),
    #"Filtered Rows8" = Table.SelectRows(#"Merged Columns1", each true),
    #"Replaced Value11" = Table.ReplaceValue(#"Filtered Rows8","","N/A",Replacer.ReplaceValue,{"Work Industry"}),
    #"Removed Columns7" = Table.RemoveColumns(#"Replaced Value11",{"Q4 - What Industry do you work in? - Copy"}),
    #"Filtered Rows9" = Table.SelectRows(#"Removed Columns7", each true),
    #"Reordered Columns2" = Table.ReorderColumns(#"Filtered Rows9",{"Unique ID", "Date Taken (America/New_York)", "Time Taken (America/New_York)", "Time Spent", "Q1 - Which Title Best Fits your Current Role?", "Q2 - Did you switch careers into Data?", "Q3 - Current Yearly Salary (in USD)", "Average Income", "Q4 - What Industry do you work in?", "Q5 - Favorite Programming Language", "Q6 - How Happy are you in your Current Position with the following? (Salary)", "Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)", "Q6 - How Happy are you in your Current Position with the following? (Coworkers)", "Q6 - How Happy are you in your Current Position with the following? (Management)", "Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)", "Q6 - How Happy are you in your Current Position with the following? (Learning New Things)", "Work Industry", "Q7 - How difficult was it for you to break into Data?", "Q8 - If you were to look for a new job today, what would be the most important thing to you?", "Q9 - Male/Female?", "Q10 - Current Age", "Country of Residence", "Q12 - Highest Level of Education", "Q13 - Ethnicity"}),
    #"Duplicated Column5" = Table.DuplicateColumn(#"Reordered Columns2", "Q4 - What Industry do you work in?", "Q4 - What Industry do you work in? - Copy"),
    #"Duplicated Column6" = Table.DuplicateColumn(#"Duplicated Column5", "Q4 - What Industry do you work in? - Copy", "Q4 - What Industry do you work in? - Copy - Copy"),
    #"Replaced Value12" = Table.ReplaceValue(#"Duplicated Column6","Other (Please Specify):","",Replacer.ReplaceText,{"Q4 - What Industry do you work in? - Copy - Copy"}),
    #"Filtered Rows10" = Table.SelectRows(#"Replaced Value12", each true),
    #"Removed Columns8" = Table.RemoveColumns(#"Filtered Rows10",{"Q4 - What Industry do you work in? - Copy", "Q4 - What Industry do you work in? - Copy - Copy"}),
    #"Filtered Rows11" = Table.SelectRows(#"Removed Columns8", each true),
    #"Duplicated Column7" = Table.DuplicateColumn(#"Filtered Rows11", "Q5 - Favorite Programming Language", "Q5 - Favorite Programming Language - Copy"),
    #"Filtered Rows12" = Table.SelectRows(#"Duplicated Column7", each true),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Filtered Rows12", "Q5 - Favorite Programming Language - Copy", Splitter.SplitTextByEachDelimiter({":"}, QuoteStyle.None, false), {"Q5 - Favorite Programming Language - Copy.1", "Q5 - Favorite Programming Language - Copy.2"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Q5 - Favorite Programming Language - Copy.1", type text}, {"Q5 - Favorite Programming Language - Copy.2", type text}}),
    #"Filtered Rows13" = Table.SelectRows(#"Changed Type5", each true),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows13",{{"Q5 - Favorite Programming Language - Copy.1", "Favorite Programming Language"}}),
    #"Filtered Rows14" = Table.SelectRows(#"Renamed Columns", each true),
    #"Removed Columns9" = Table.RemoveColumns(#"Filtered Rows14",{"Q5 - Favorite Programming Language - Copy.2"}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns9",{"Unique ID", "Date Taken (America/New_York)", "Time Taken (America/New_York)", "Time Spent", "Q1 - Which Title Best Fits your Current Role?", "Q2 - Did you switch careers into Data?", "Q3 - Current Yearly Salary (in USD)", "Average Income", "Q4 - What Industry do you work in?", "Q5 - Favorite Programming Language", "Q6 - How Happy are you in your Current Position with the following? (Salary)", "Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)", "Q6 - How Happy are you in your Current Position with the following? (Coworkers)", "Q6 - How Happy are you in your Current Position with the following? (Management)", "Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)", "Q6 - How Happy are you in your Current Position with the following? (Learning New Things)", "Work Industry", "Q7 - How difficult was it for you to break into Data?", "Favorite Programming Language", "Q8 - If you were to look for a new job today, what would be the most important thing to you?", "Q9 - Male/Female?", "Q10 - Current Age", "Country of Residence", "Q12 - Highest Level of Education", "Q13 - Ethnicity"}),
    #"Filtered Rows15" = Table.SelectRows(#"Reordered Columns3", each true),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Filtered Rows15", {{"Date Taken (America/New_York)", #date(1, 1, 1)}}),
    #"Filtered Rows16" = Table.SelectRows(#"Replaced Errors", each true)
in
    #"Filtered Rows16"
